services:
  db:
    image: postgres:16-alpine
    container_name: transporte_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transporte
    ports:
      - "5432:5432"
    volumes:
      - transporte_pgdata:/var/lib/postgresql/data

volumes:
  transporte_pgdata:
