-- Guía de Remisión electrónica del transportista, por viaje — aditivo.
CREATE TABLE "guias_transportista" (
    "id" TEXT NOT NULL,
    "sedeId" TEXT NOT NULL,
    "viajeId" TEXT NOT NULL,
    "serie" TEXT NOT NULL DEFAULT '',
    "correlativo" TEXT NOT NULL DEFAULT '',
    "tipoGur" TEXT NOT NULL DEFAULT '31',
    "fechaEmision" DATE,
    "fechaTraslado" DATE,
    "partidaDir" TEXT NOT NULL DEFAULT '',
    "partidaUbigeo" TEXT NOT NULL DEFAULT '',
    "llegadaDir" TEXT NOT NULL DEFAULT '',
    "llegadaUbigeo" TEXT NOT NULL DEFAULT '',
    "remitenteRuc" TEXT NOT NULL DEFAULT '',
    "remitenteRazon" TEXT NOT NULL DEFAULT '',
    "destinatarioRuc" TEXT NOT NULL DEFAULT '',
    "destinatarioRazon" TEXT NOT NULL DEFAULT '',
    "conductorNombre" TEXT NOT NULL DEFAULT '',
    "conductorDni" TEXT NOT NULL DEFAULT '',
    "conductorLicencia" TEXT NOT NULL DEFAULT '',
    "placaTracto" TEXT NOT NULL DEFAULT '',
    "tucTracto" TEXT NOT NULL DEFAULT '',
    "placaCarreta" TEXT NOT NULL DEFAULT '',
    "tucCarreta" TEXT NOT NULL DEFAULT '',
    "pesoBruto" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "unidad" TEXT NOT NULL DEFAULT 'KGM',
    "docRefTipo" TEXT NOT NULL DEFAULT '09',
    "docRefNumero" TEXT NOT NULL DEFAULT '',
    "pagadorFlete" TEXT NOT NULL DEFAULT 'remitente',
    "terceroRuc" TEXT NOT NULL DEFAULT '',
    "terceroRazon" TEXT NOT NULL DEFAULT '',
    "trasladoTotal" BOOLEAN NOT NULL DEFAULT true,
    "observaciones" TEXT NOT NULL DEFAULT '',
    "itemsJson" TEXT NOT NULL DEFAULT '[]',
    "estadoDocumento" TEXT NOT NULL DEFAULT '',
    "sunatDescripcion" TEXT NOT NULL DEFAULT '',
    "hash" TEXT NOT NULL DEFAULT '',
    "cdr" TEXT,
    "xml" TEXT,
    "emitidoEn" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "guias_transportista_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "guias_transportista_sedeId_idx" ON "guias_transportista"("sedeId");
CREATE INDEX "guias_transportista_viajeId_idx" ON "guias_transportista"("viajeId");
